
name: Trivy Scan

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy
        run: |
          docker run --rm -v $PWD:/project aquasec/trivy:latest fs --severity HIGH,CRITICAL --no-progress /project
